# Generated by Django 5.1.6 on 2025-02-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=70)),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo'), ('S', 'Suspenso')], max_length=1)),
                ('data_alteracao', models.DateTimeField(verbose_name='data alteração')),
            ],
        ),
    ]
