# Generated by Django 5.1.6 on 2025-02-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=75),
        ),
    ]
