# Generated by Django 5.1.6 on 2025-02-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0004_alter_usuario_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='situacao',
            field=models.CharField(max_length=1),
        ),
    ]
