# Generated by Django 5.1.6 on 2025-02-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0005_alter_usuario_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='situacao',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo'), ('S', 'Suspenso'), ('O', 'outro')], default='A', max_length=1),
        ),
    ]
