# Generated by Django 5.1.6 on 2025-02-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0006_alter_usuario_login_alter_usuario_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='situacao',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1),
        ),
    ]
